name: FastAPI Deployment and Lambda Update

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"  # Ajusta la versión según tu Lambda (3.10 recomendado)

      # Paso 3: Instalar dependencias en una carpeta específica
      - name: Install dependencies for Lambda
        run: |
          python -m pip install --upgrade pip
          mkdir -p lambda_dependencies
          pip install -r requirements.txt -t lambda_dependencies

      # Paso 4: Crear archivo ZIP
      - name: Package dependencies into ZIP
        run: |
          cd lambda_dependencies
          zip -r ../lambda_dependencies.zip .
          cd ..

      # Paso 5: Subir a S3
      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp lambda_dependencies.zip s3://zipapiparcial/lambda_dependencies.zip

      # Paso 6: Actualizar Lambda
      - name: Update Lambda Function
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws lambda update-function-code \
            --function-name prueba \
            --s3-bucket zipapiparcial \
            --s3-key lambda_dependencies.zip
